# Fibonacci List
# Description
# The Fibonacci List is the list of numbers: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, … The next number is generated by adding up the two numbers before it. Build a function FibLst which takes an integer n as input and returns an n-element Fibonacci List. If n is less than 1, returns -1.

# Examples
# FibLst(1) returns [0]
# FibLst(3) returns [0, 1, 1]
# FibLst(6) returns [0, 1, 1, 2, 3, 5]
# FibLst(-3) returns -1

def FibLst(n):
    if n<1:
        return -1
    elif n==1:
        return [0]
    elif n==2:
        return [0,1]
    else:
        newlist = [0,1]
        for i in range(2,n):
            newlist.append(newlist[i-1] + newlist[i-2])
        return newlist
